version: '3.8'

services:
  stremio-import:
    build: .
    container_name: stremio-import-automation
    restart: unless-stopped
    environment:
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - SCHEDULE_SECONDS=${SCHEDULE_SECONDS:-7200}
    volumes:
      # Optional: Mount logs directory if you want to persist logs
      - ./logs:/usr/src/app/logs
    # Optional: Add resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
    # Optional: Health check
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Health check')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
