version: '3.8'

services:
  stremio-import:
    build: .
    environment:
      - EMAIL=${EMAIL}
      - PASSWORD=${PASSWORD}
      - SCHEDULE_SECONDS=${SCHEDULE_SECONDS:-7200}
    restart: unless-stopped
