services:
  stremio-import:
    build: .
    image: stremio-import:latest
    container_name: stremio-import
    environment:
      - EMAIL=your-stremio-email@example.com
      - PASSWORD=your-stremio-password
      - SCHEDULE_SECONDS=7200
    restart: unless-stopped